node {
    git url: 'https://github.com/WisWang/wis', branch: 'master'
    stage('docker image build') {
        sh """
            cd homework
            cp -f app.war docker/app
            docker build -t wis/app1:$BUILD_NUMBER docker/app 
            """
        sh "kind load docker-image wis/app1:$BUILD_NUMBER"
        sh """
            cd homework
            echo $BUILD_NUMBER > static/version.html
            zip static static
            cp -rf static docker/static
            docker build -t wis/static:$BUILD_NUMBER  docker/static 
            """
        sh "kind load docker-image wis/static:$BUILD_NUMBER"        
    }
    stage('dev') {
        sh """
            sudo /root/.kubectx/kubens dev
            sudo kubectl set image deployment/app1 app-war=wis/app1:$BUILD_NUMBER
            sudo kubectl set image deployment/static app-static=wis/static:$BUILD_NUMBER
        """
        sh """
            sleep 10
            curl static.dev.wis.com/version.html
        """
        echo "check is app pass unit test and intergration test"
        echo "tag docker image dev pass"
        echo "dev stage pass"

    }
    stage('test') {
        sh """
            sudo /root/.kubectx/kubens test
            sudo kubectl set image deployment/app1 app-war=wis/app1:$BUILD_NUMBER
            sudo kubectl set image deployment/static app-static=wis/static:$BUILD_NUMBER
        """
        sh """
            sleep 10
            curl static.test.wis.com/version.html
        """
        echo "check if app pass accept test"
        echo "tag docker image dev pass"
        echo "test stage pass"
    }
    stage('prod') {
        echo "deploy to prod"
    }


}