apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: wiswang/go-web-hello-world:v0.1
        ports:
        - containerPort: 8081
--- 
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 31080
  selector:
    app: app1
